[tool.poetry]
name = "faviscore"
version = "0.1.0"
description = ""
authors = ["Pius von Däniken <vode@zhaw.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
